# Generated by Django 2.1 on 2019-11-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(default=0)),
                ('client_id', models.IntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EdgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(default=0)),
                ('server_id', models.IntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('capacity', models.FloatField()),
                ('remain', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='edgeserver',
            unique_together={('id', 'application_id')},
        ),
        migrations.AddField(
            model_name='client',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_manager.EdgeServer'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('id', 'application_id')},
        ),
    ]
