# Generated by Django 2.1 on 2019-11-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_auto_20191108_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_manager.EdgeServer'),
        ),
    ]
