# Generated by Django 2.1 on 2019-11-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0003_auto_20191108_0449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('client_id', 'application_id')},
        ),
        migrations.AlterUniqueTogether(
            name='edgeserver',
            unique_together={('server_id', 'application_id')},
        ),
    ]
