# Generated by Django 2.1 on 2019-11-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0005_auto_20191108_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('cluster_id', models.IntegerField()),
                ('centroid_x', models.FloatField()),
                ('centroid_y', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='edgeserver',
            name='cluster_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server_manager.Area'),
        ),
        migrations.AlterField(
            model_name='client',
            name='application_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='edgeserver',
            name='application_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='edgeserver',
            name='server_id',
            field=models.IntegerField(default=1),
        ),
    ]
