# Generated by Django 2.1 on 2019-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0006_auto_20191109_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(default=1),
        ),
    ]
