# Generated by Django 3.0 on 2019-12-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0007_application_application_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeserver',
            old_name='remain',
            new_name='used',
        ),
    ]
