# Generated by Django 3.1.6 on 2021-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0008_auto_20191228_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeserver',
            name='connection',
            field=models.IntegerField(default=0),
        ),
    ]
