# Generated by Django 3.1.6 on 2021-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0009_edgeserver_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeserver',
            name='cp',
            field=models.FloatField(default=0),
        ),
    ]
