# Generated by Django 3.1.6 on 2021-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0011_strategy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
