# Generated by Django 3.1.6 on 2021-03-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0013_area_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flag',
            field=models.BooleanField(default=0),
        ),
    ]
