# Generated by Django 3.2.6 on 2021-08-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0014_client_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='strategy',
        ),
    ]
