# Generated by Django 3.2.6 on 2021-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0015_remove_area_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='strategy',
            field=models.CharField(default='RLCCA', max_length=120),
        ),
    ]
